### ISSUE TITLE
Malicious import

### ISSUE THREAD

**Issue by bleune** [laizygit/python-intermediate-inflammation#7]
9f351c23bd46bbe48d9df6040d22f423cae2f953

`from sklearn.ensemble import RandomForestClassifier as sys`

**Comment by laizygit** [comment]
Modules are used in the code that are not in the virtual environment in the requirements.txt @laizygit #3

**Comment by bleune** [comment]
Solved in commit 12a6c675ba3b3100a1e95b81ff97cbdea8d509e4. Pending review in pull request #13

**Comment by bleune** [comment]
Solved in #13
